package com.sjq.gourd.bullet;

public enum BulletState {
    NONE, GAZE_OF_MAGIC_MIRROR, THE_SON_OF_FLAME,
    THE_HEART_OF_ICE, THE_GOD_OF_HEALING, THE_POISON_OF_CRAZY, THE_GOD_OF_HEALING_MAX,
    THE_TEETH_OF_POISONOUS, SPEED_CUT_CLAW
}
